version: '3.7'
services:
        backend-api:
                build: 
                        context: "./backend"
                ports:
                        - "8000:8000"
                volumes:
                        - ../../RHT-Core/.:/app
                        - ../../static/.:/static
                tty: true
